[package]
name = "kftray-utils"
version = "0.0.1"
edition = "2021"

[workspace]

[[bin]]
name = "bump_version"
path = "src/bump_version.rs"

[[bin]]
name = "generate_icons"
path = "src/generate_icons.rs"

[dependencies]
ico = "0.4"
image = "0.25"
regex = "1"
serde_json = "1"
thiserror = "2"
