[package]
name = "kftray-server"
version = "0.9.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.4"
log = "0.4"
env_logger = "0.11.2"
byteorder = "1.4"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
mockall = "0.12"